# Generated by Django 5.1.4 on 2024-12-07 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('excerpt', models.CharField(max_length=728)),
                ('content', models.TextField()),
                ('author_name', models.CharField(max_length=128)),
                ('post_image', models.ImageField(upload_to='PostImages/')),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('post_slug', models.SlugField(max_length=200, unique=True)),
                ('post_thumbnail', models.ImageField(blank=True, upload_to='PostThumbnails/')),
                ('post_tag', models.CharField(max_length=128)),
                ('post_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=10)),
                ('views', models.PositiveIntegerField(default=0)),
                ('comments_enabled', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
