# Generated by Django 5.1.4 on 2024-12-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsVault', '0003_alter_blogpost_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_image',
            field=models.ImageField(upload_to='PostImages/'),
        ),
    ]
