# Generated by Django 5.1.4 on 2024-12-08 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsVault', '0004_alter_blogpost_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='post_slug',
            field=models.SlugField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='post_tag',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
