# Generated by Django 5.1.4 on 2024-12-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsVault', '0005_alter_blogpost_post_slug_alter_blogpost_post_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(max_length=80),
        ),
    ]
