# Generated by Django 5.1.4 on 2024-12-17 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PostsVault', '0006_alter_blogpost_excerpt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='excerpt',
            field=models.CharField(max_length=500),
        ),
    ]
