# Generated by Django 5.1.4 on 2024-12-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImgBox', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imgboxdb',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
