# Generated by Django 5.1.4 on 2024-12-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='user_file',
            field=models.FileField(blank=True, upload_to='document/'),
        ),
    ]
