# Generated by Django 5.1.4 on 2024-12-27 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeManager', '0002_resume_user_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='state',
        ),
    ]
