# Generated by Django 5.1.4 on 2024-12-27 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ResumeManager', '0006_alter_resume_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='gender',
            field=models.CharField(max_length=10),
        ),
    ]
