# Generated by Django 5.1.3 on 2025-01-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ZoomShop', '0002_rename_order_deliverd_date_placedorderdb_order_delivered_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdb',
            name='product_image',
            field=models.ImageField(upload_to='media/productImage'),
        ),
    ]
